# Default parameters file
# This files contains all parameters and their default values.

# ImageParameters
channel_junction: 0
channel_nucleus: 1
channel_organelle: 2
channel_expression_marker: -1 # -1 means no expression marker
pixel_to_micron_ratio: 1.0

# RuntimeParameter
extract_group_features: False
membrane_thickness: 5
feature_of_interest: "cell_area"
min_cell_size: 50
min_nucleus_size: 10
min_organelle_size: 10
dp_epsilon: 5
cue_direction: 0
connection_graph: True
segmentation_algorithm: "CellposeSegmenter" # "CellposeSegmenter", "SamSegmenter"
remove_small_objects_size: 10 # in pixels, put to 0 to disable
clear_border: True
keyfile_condition_cols: ["short_name"] # only needed if run_key option is used


# PlotParameter
plot_junctions: True
plot_polarity: True
plot_orientation: True
plot_marker: True
plot_ratio_method: True
plot_cyclic_orientation: True
plot_foi: True
outline_width: 2
show_polarity_angles: True
show_graphics_axis: False
plot_scalebar: True
length_scalebar_microns: 20.0
graphics_output_format: ["png"] # 'png', 'pdf', 'svg'
dpi: 300
graphics_width: 5 # figure width in inches
graphics_height: 5 # figure height in inches
length_unit: "pixel" # "microns"
fontsize_text_annotations: 6
font_color: "w"
marker_size: 2
